services:
  postgres:
    image: postgres:latest
    container_name: myshop-springboot
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - myshop:/var/lib/postgresql/data

volumes:
  myshop: