spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp